apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
      - name: master
        image: master-image
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: master-service
spec:
  type: ClusterIP
  selector:
    app: master
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
